### ISSUE TITLE
Component: Card

### ISSUE THREAD

**Issue by NaveenKharwar** [manjumjn/tailwindify#12]
I'd love to create a card component. Please add the appropriate labels to this issue and assign it to me. Thank you.

**Comment by manjumjn** [comment]
@NaveenKharwar Please check the updated readme and guideline. To avoid the confusion on naming new component we have updated it. Feel free to create a PR for the component according to  the updated [Contributing Guide](https://github.com/manjumjn/tailwindify/blob/main/CONTRIBUTING.md)
