### ISSUE TITLE
What are the differences between main and master branch? 

### ISSUE THREAD

**Issue by raunakhajela** [manjumjn/tailwindify#9]
I see two branches i.e. main, and master, Are their any significant differences between both the branches or you plan to delete one? 

Also, can we create a new branch depending on the new component we're working on?

**Comment by manjumjn** [comment]
No difference, It's default branches. Deleted `master` branch, For new components you can create new branch and create PR for the same

**Comment by raunakhajela** [comment]
Alright, thanks!
